# Contents
> 20 November 2023
* Setup
* Tensors
* Variables
* Math
* Gradients

## Setup

In [2]:
import tensorflow as tf
import keras
import numpy as np

## Tensors

* Tensor: N-dimensional array
### Numpy vs TensorFlow
* TensorFlow can leverage hardware accelerators such as GPUs and TPUs.
* TensorFlow can automatically compute the gradient of arbitrary differentiable tensor expressions.
* TensorFlow computation can be distributed to large numbers of devices on a single machine, and large number of machines (potentially with multiple devices each).

In [5]:
def print_sep(num=20):
    print(num*'--')

In [7]:
# constant tensor
x = tf.constant([[1, 2],[3,4]])
print(x)
print_sep()

# converting to numpy array
x_np = x.numpy()
print(x_np)
print_sep()

# shape and dtype (like numpy)
print(f"type:\t{x.shape}\nshape:\t{x.dtype}")
print(f"type:\t{x_np.shape}\nshape:\t{x_np.dtype}")
print_sep()

# ones and zeros (like numpy)
print(tf.ones(shape=(3,1)))
print_sep()
print(tf.zeros(shape=(2,2)))
print_sep()

# random constant tensors
x_randNorm = tf.random.normal(shape=(1,4), mean=0.0, stddev=1.0)
print(x_randNorm)
print_sep()
x_randUni = tf.random.uniform(shape=(2,2), minval=2, maxval=5)
print(x_randUni)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
----------------------------------------
[[1 2]
 [3 4]]
----------------------------------------
type:	(2, 2)
shape:	<dtype: 'int32'>
type:	(2, 2)
shape:	int32
----------------------------------------
tf.Tensor(
[[1.]
 [1.]
 [1.]], shape=(3, 1), dtype=float32)
----------------------------------------
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
----------------------------------------
tf.Tensor([[ 1.1965895   0.3578922  -0.19351485 -0.45781013]], shape=(1, 4), dtype=float32)
----------------------------------------
tf.Tensor(
[[3.9602199 4.0469484]
 [3.0538282 3.6466255]], shape=(2, 2), dtype=float32)


## Variables

* Variables are special tensors used to store mutable state (such as the weights of a neural network).

In [10]:
# Variable
init_val = tf.random.normal(shape=(2,2))
print(init_val)
print_sep()
a_var = tf.Variable(init_val)
print(a_var)
print_sep()

# assign
new_val = tf.random.normal(shape=(2,2))
print(new_val)
print_sep()
a_var.assign(new_val)
print(a_var)
print_sep()

# increment with new: assign_add
a_var.assign_add(tf.ones(shape=(2,2))*2)
print(a_var)
print_sep()

# decrement with new: assign_sub
a_var.assign_sub(tf.ones(shape=(2,2)))
print(a_var)

tf.Tensor(
[[ 0.9368381   1.0124143 ]
 [ 0.96799594 -1.0253472 ]], shape=(2, 2), dtype=float32)
----------------------------------------
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.9368381 ,  1.0124143 ],
       [ 0.96799594, -1.0253472 ]], dtype=float32)>
----------------------------------------
tf.Tensor(
[[ 1.8276376  -0.52430665]
 [ 1.0001394  -0.68555915]], shape=(2, 2), dtype=float32)
----------------------------------------
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.8276376 , -0.52430665],
       [ 1.0001394 , -0.68555915]], dtype=float32)>
----------------------------------------
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[3.8276377, 1.4756933],
       [3.0001392, 1.3144408]], dtype=float32)>
----------------------------------------
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2.8276377 , 0.47569335],
       [2.0001392 , 0.31444085]], dtype=float32)>


## Maths

In [12]:
a = tf.random.normal(shape=(2,2))
b = tf.ones(shape=(2,2))
print(a)
print(b)
print_sep()

# a + b
c = a + b
print(c)
print_sep()

# c^2
c_sq = tf.square(c)
print(c_sq)
print_sep()

# e^c_sq
e_csq = tf.exp(c_sq)
print(e_csq)

tf.Tensor(
[[ 0.7957157  -1.3118519 ]
 [-0.90906024  0.53265214]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
----------------------------------------
tf.Tensor(
[[ 1.7957157  -0.31185186]
 [ 0.09093976  1.5326521 ]], shape=(2, 2), dtype=float32)
----------------------------------------
tf.Tensor(
[[3.2245948  0.09725158]
 [0.00827004 2.3490226 ]], shape=(2, 2), dtype=float32)
----------------------------------------
tf.Tensor(
[[25.143383   1.1021376]
 [ 1.0083044 10.475327 ]], shape=(2, 2), dtype=float32)


## Gradient

* Here's another big difference with NumPy: you can automatically retrieve the gradient of any differentiable expression.

In [15]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
print(a,b)
print_sep()

# c = square_root of (a^2 + b^2)
# find first derivative of c wrt a
with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a) + tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)
    print_sep()

# if 'Variable', then no need to watch manually (automatically watched)
a = tf.Variable(a)
with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a) + tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)
    print_sep()

# compute higher order derivative like 2nd derivative by nesting tape
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a) + tf.square(b))
        dc_da = tape.gradient(c,a)
        print(dc_da)
        print_sep()
    d2c_d2a = outer_tape.gradient(dc_da,a)
    print(d2c_d2a)

tf.Tensor(
[[ 0.740372    0.11314937]
 [ 0.6025739  -0.8957461 ]], shape=(2, 2), dtype=float32) tf.Tensor(
[[ 0.9104634   1.6426238 ]
 [-0.36554867 -1.6070887 ]], shape=(2, 2), dtype=float32)
----------------------------------------
tf.Tensor(
[[ 0.63091105  0.06872047]
 [ 0.8549761  -0.48685482]], shape=(2, 2), dtype=float32)
----------------------------------------
tf.Tensor(
[[ 0.63091105  0.06872047]
 [ 0.8549761  -0.48685482]], shape=(2, 2), dtype=float32)
----------------------------------------
tf.Tensor(
[[ 0.63091105  0.06872047]
 [ 0.8549761  -0.48685482]], shape=(2, 2), dtype=float32)
----------------------------------------
tf.Tensor(
[[0.5129552  0.6044748 ]
 [0.38169944 0.41468984]], shape=(2, 2), dtype=float32)
